/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.practica7.lucerojustin.tacurijhonatan.vista.compositor;

import ec.edu.ups.practica7.lucerojustin.tacurijhonatan.controlador.ControladorCompositor;
import ec.edu.ups.practica7.lucerojustin.tacurijhonatan.modelo.Cancion;
import ec.edu.ups.practica7.lucerojustin.tacurijhonatan.modelo.Compositor;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Usuario
 */
public class BuscarPorTitulo extends javax.swing.JInternalFrame {
    private ControladorCompositor controladorCompositor;
    private ResourceBundle mensajes;
    private Compositor compositorTempo;
    /**
     * Creates new form BuscarPorTitulo
     */
    public BuscarPorTitulo(ControladorCompositor controladorCompositor) {
        initComponents();
        this.controladorCompositor = controladorCompositor;
        
    }

    public void cambiarIdioma(Locale localizacion){
        mensajes = ResourceBundle.getBundle("mensajes.mensaje", localizacion);
        jblIdBuscarPorTitulo.setText(mensajes.getString("ventana.id"));
        jblNombreBuscarPorTitulo.setText(mensajes.getString("ventana.nombre"));
        jblApellidoBuscarPorTitulo.setText(mensajes.getString("ventana.apellido"));
        jblEdadBuscarPorTitulo.setText(mensajes.getString("ventana.edad"));
        jblSalarioBuscarPorTitulo.setText(mensajes.getString("ventana.salario"));
        jblNacionalidadBuscarPorTitulo.setText(mensajes.getString("ventana.nacionalidad"));
        jblNumeroComposicionesBuscarPorTitulo.setText(mensajes.getString("ventanaCompositor.numerocomposiciones"));
        btnAceptar.setText(mensajes.getString("boton.buscar"));
        btnCancelar.setText(mensajes.getString("boton.cancelar"));
        Border borde = BorderFactory.createTitledBorder(mensajes.getString("panel.buscarportitulo"));
        jpanelA.setBorder(borde);
        TableColumnModel columnModel = tblCancion.getColumnModel();
        TableColumn columnaCodigo = columnModel.getColumn(0);
        columnaCodigo.setHeaderValue(mensajes.getString("ventana.codigo"));
        TableColumn columnaLetra = columnModel.getColumn(1);
        columnaLetra.setHeaderValue(mensajes.getString("ventanaCancion.letra"));
        TableColumn columnaTitulo = columnModel.getColumn(2);
        columnaTitulo.setHeaderValue(mensajes.getString("ventanaCancion.titulo"));
        TableColumn columnaDuracion = columnModel.getColumn(3);
        columnaDuracion.setHeaderValue(mensajes.getString("ventanaCancion.duracioncancion"));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jpanelA = new javax.swing.JPanel();
        jblIdBuscarPorTitulo = new javax.swing.JLabel();
        jblNombreBuscarPorTitulo = new javax.swing.JLabel();
        jblApellidoBuscarPorTitulo = new javax.swing.JLabel();
        jblEdadBuscarPorTitulo = new javax.swing.JLabel();
        jblNacionalidadBuscarPorTitulo = new javax.swing.JLabel();
        jblSalarioBuscarPorTitulo = new javax.swing.JLabel();
        jblNumeroComposicionesBuscarPorTitulo = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtNacionalidad = new javax.swing.JTextField();
        txtSalario = new javax.swing.JTextField();
        txtNumeroComposiciones = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jblTItuloCancionBuscarPorTitulo = new javax.swing.JLabel();
        txtTituloCancion = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCancion = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Letra", "Título", "Duración de Canción"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jpanelA.setBorder(javax.swing.BorderFactory.createTitledBorder("BUSCAR POR TÍTULO DE CANCIÓN"));
        jpanelA.setLayout(null);

        jblIdBuscarPorTitulo.setText("ID:");
        jpanelA.add(jblIdBuscarPorTitulo);
        jblIdBuscarPorTitulo.setBounds(60, 55, 14, 16);

        jblNombreBuscarPorTitulo.setText("Nombre:");
        jpanelA.add(jblNombreBuscarPorTitulo);
        jblNombreBuscarPorTitulo.setBounds(60, 89, 47, 16);

        jblApellidoBuscarPorTitulo.setText("Apellido:");
        jpanelA.add(jblApellidoBuscarPorTitulo);
        jblApellidoBuscarPorTitulo.setBounds(60, 123, 47, 16);

        jblEdadBuscarPorTitulo.setText("Edad:");
        jpanelA.add(jblEdadBuscarPorTitulo);
        jblEdadBuscarPorTitulo.setBounds(60, 163, 29, 16);

        jblNacionalidadBuscarPorTitulo.setText("Nacionalidad:");
        jpanelA.add(jblNacionalidadBuscarPorTitulo);
        jblNacionalidadBuscarPorTitulo.setBounds(60, 197, 73, 16);

        jblSalarioBuscarPorTitulo.setText("Salario:");
        jpanelA.add(jblSalarioBuscarPorTitulo);
        jblSalarioBuscarPorTitulo.setBounds(60, 231, 38, 16);

        jblNumeroComposicionesBuscarPorTitulo.setText("Numero de Composiciones:");
        jpanelA.add(jblNumeroComposicionesBuscarPorTitulo);
        jblNumeroComposicionesBuscarPorTitulo.setBounds(60, 265, 148, 16);

        txtId.setEnabled(false);
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        jpanelA.add(txtId);
        txtId.setBounds(214, 52, 131, 22);

        txtNombre.setEditable(false);
        txtNombre.setEnabled(false);
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jpanelA.add(txtNombre);
        txtNombre.setBounds(214, 86, 131, 22);

        txtApellido.setEditable(false);
        txtApellido.setEnabled(false);
        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        jpanelA.add(txtApellido);
        txtApellido.setBounds(214, 120, 131, 22);

        txtEdad.setEditable(false);
        txtEdad.setEnabled(false);
        txtEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadActionPerformed(evt);
            }
        });
        jpanelA.add(txtEdad);
        txtEdad.setBounds(214, 160, 131, 22);

        txtNacionalidad.setEditable(false);
        txtNacionalidad.setEnabled(false);
        txtNacionalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNacionalidadActionPerformed(evt);
            }
        });
        jpanelA.add(txtNacionalidad);
        txtNacionalidad.setBounds(214, 194, 131, 22);

        txtSalario.setEditable(false);
        txtSalario.setEnabled(false);
        txtSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalarioActionPerformed(evt);
            }
        });
        jpanelA.add(txtSalario);
        txtSalario.setBounds(214, 228, 131, 22);

        txtNumeroComposiciones.setEditable(false);
        txtNumeroComposiciones.setEnabled(false);
        txtNumeroComposiciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroComposicionesActionPerformed(evt);
            }
        });
        jpanelA.add(txtNumeroComposiciones);
        txtNumeroComposiciones.setBounds(214, 262, 131, 22);

        btnAceptar.setText("Buscar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jpanelA.add(btnAceptar);
        btnAceptar.setBounds(162, 311, 72, 23);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jpanelA.add(btnCancelar);
        btnCancelar.setBounds(269, 311, 76, 23);

        jblTItuloCancionBuscarPorTitulo.setText("Ingrese el nombre de la cancion para encontrar a su comporsitor:");
        jpanelA.add(jblTItuloCancionBuscarPorTitulo);
        jblTItuloCancionBuscarPorTitulo.setBounds(11, 27, 343, 16);
        jpanelA.add(txtTituloCancion);
        txtTituloCancion.setBounds(372, 24, 148, 22);

        tblCancion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Letra", "Título", "Duración de Canción"
            }
        ));
        jScrollPane2.setViewportView(tblCancion);

        jpanelA.add(jScrollPane2);
        jScrollPane2.setBounds(380, 70, 460, 290);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imgen.jpg"))); // NOI18N
        jpanelA.add(jLabel1);
        jLabel1.setBounds(10, 0, 870, 410);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelA, javax.swing.GroupLayout.DEFAULT_SIZE, 891, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpanelA, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void txtEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadActionPerformed

    private void txtNacionalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNacionalidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNacionalidadActionPerformed

    private void txtSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalarioActionPerformed

    private void txtNumeroComposicionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroComposicionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroComposicionesActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        if (txtTituloCancion.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, mensajes.getString("joption.notitulo")); 
        }else{
            Compositor compositorTempo = controladorCompositor.buscarPorTituloCancion(txtTituloCancion.getText()); 
            if (compositorTempo !=null) {
                txtId.setText(String.valueOf(compositorTempo.getCodigo())); 
                txtNombre.setText(compositorTempo.getNombre());
                txtApellido.setText(compositorTempo.getApellido());
                txtEdad.setText( String.valueOf(compositorTempo.getEdad()));
                txtNacionalidad.setText(compositorTempo.getNacionalidad());
                txtNacionalidad.setText(compositorTempo.getNacionalidad());
                txtSalario.setText(String.valueOf(compositorTempo.calcularSalario()));
                txtNumeroComposiciones.setText(String.valueOf(compositorTempo.getNumeroDeComposiciones()));
                this.actualizarTabla();
            }else{
                this.limpiarCampos();
                JOptionPane.showMessageDialog(this, mensajes.getString("joption.noexistetitulo"));  

            }
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        txtId.setText("");
        this.limpiarCampos();
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    
    private void actualizarTabla(){
        DefaultTableModel modelo = (DefaultTableModel)this.tblCancion.getModel();
        modelo.setNumRows(0);
        List <Cancion> listaCan = compositorTempo.getCancionesTop100Billboard();
        //if (listaPersonas!=null) {
            for (Cancion listaCa : listaCan) {
                int cod = listaCa.getCodigo();
                String nom = listaCa.getTitulo();
                String letra= listaCa.getLetra();
                double duracion = listaCa.getTiempoEnMinutos();
                Object[] rowDate = {cod,nom,letra,duracion};
                modelo.addRow(rowDate);
            }
            this.tblCancion.setModel(modelo);
        //}else{
          //  JOptionPane.showMessageDialog(this, "No se ha ingresado ningun cantante aun");
        //}
    }
    
    private void limpiarCampos(){
        txtTituloCancion.setText(""); 
        txtId.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtEdad.setText("");
        txtNacionalidad.setText("");
        txtSalario.setText("");
        txtNumeroComposiciones.setText("");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jblApellidoBuscarPorTitulo;
    private javax.swing.JLabel jblEdadBuscarPorTitulo;
    private javax.swing.JLabel jblIdBuscarPorTitulo;
    private javax.swing.JLabel jblNacionalidadBuscarPorTitulo;
    private javax.swing.JLabel jblNombreBuscarPorTitulo;
    private javax.swing.JLabel jblNumeroComposicionesBuscarPorTitulo;
    private javax.swing.JLabel jblSalarioBuscarPorTitulo;
    private javax.swing.JLabel jblTItuloCancionBuscarPorTitulo;
    private javax.swing.JPanel jpanelA;
    private javax.swing.JTable tblCancion;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNacionalidad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumeroComposiciones;
    private javax.swing.JTextField txtSalario;
    private javax.swing.JTextField txtTituloCancion;
    // End of variables declaration//GEN-END:variables
}
