/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.practica7.lucerojustin.tacurijhonatan.vista.cantante;

import ec.edu.ups.practica7.lucerojustin.tacurijhonatan.controlador.ControladorCantante;
import ec.edu.ups.practica7.lucerojustin.tacurijhonatan.modelo.Cantante;
import ec.edu.ups.practica7.lucerojustin.tacurijhonatan.modelo.Disco;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author venot
 */
public class ActualizarCantante extends javax.swing.JInternalFrame {
    private ControladorCantante controladorCantante;
    private List<Disco> listaDiscos;
    private ResourceBundle mensajes;
    /**
     * Creates new form ActualizarCantante
     */
    public ActualizarCantante(ControladorCantante controladorCantante) {
        initComponents();
        this.controladorCantante = controladorCantante;
        
    }
    
    public void cambiarIdioma(Locale localizacion){
        mensajes = ResourceBundle.getBundle("mensajes.mensaje", localizacion);
        jblIdActualizarCantante.setText(mensajes.getString("ventana.id"));
        jblNombreActualizarCantante.setText(mensajes.getString("ventana.nombre"));
        jblApellidoActualizarCantante.setText(mensajes.getString("ventana.apellido"));
        jblEdadActualizarCantante.setText(mensajes.getString("ventana.edad"));
        jblSalarioActualizarCantante.setText(mensajes.getString("ventana.salario"));
        jblNacionalidadActualizarCantante.setText(mensajes.getString("ventana.nacionalidad"));
        jblGeneroMusicalActualizarCantante.setText(mensajes.getString("ventanaCantante.generomusical"));
        jblNumeroConciertosActualizarCantante.setText(mensajes.getString("ventanaCantante.numeroconciertos"));
        jblNumeroGiras.setText(mensajes.getString("ventanaCantante.numerogiras"));
        jblNumeroSencillosActualizarCantante.setText(mensajes.getString("ventanaCantante.numerosencillos"));
        jblNombreArtisticoActualizarCantante.setText(mensajes.getString("ventanaCantante.nombreartistico"));
        btnCancelar.setText(mensajes.getString("boton.cancelar"));
        bntActualizar.setText(mensajes.getString("boton.actualizar"));
        bntBuscar.setText(mensajes.getString("boton.buscar")); 
        Border borde = BorderFactory.createTitledBorder(mensajes.getString("panel.actualizarcantante"));
        jpanelA.setBorder(borde);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelA = new javax.swing.JPanel();
        txtNumeroSencillos = new javax.swing.JTextField();
        jblNumeroConciertosActualizarCantante = new javax.swing.JLabel();
        txtNumeroConciertos = new javax.swing.JTextField();
        jblNumeroGiras = new javax.swing.JLabel();
        txtNumeroGiras = new javax.swing.JTextField();
        jblIdActualizarCantante = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        bntActualizar = new javax.swing.JButton();
        jblNombreActualizarCantante = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        jblApellidoActualizarCantante = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jblEdadActualizarCantante = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        jblNacionalidadActualizarCantante = new javax.swing.JLabel();
        txtNacionalidad = new javax.swing.JTextField();
        jblSalarioActualizarCantante = new javax.swing.JLabel();
        txtSalario = new javax.swing.JTextField();
        jblNombreArtisticoActualizarCantante = new javax.swing.JLabel();
        txtNombreArtistico = new javax.swing.JTextField();
        jblGeneroMusicalActualizarCantante = new javax.swing.JLabel();
        txtGeneroMusical = new javax.swing.JTextField();
        jblNumeroSencillosActualizarCantante = new javax.swing.JLabel();
        bntBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jpanelA.setBorder(javax.swing.BorderFactory.createTitledBorder("ACTUALZIAR CANTANTE"));
        jpanelA.setLayout(null);

        txtNumeroSencillos.setEnabled(false);
        jpanelA.add(txtNumeroSencillos);
        txtNumeroSencillos.setBounds(280, 340, 164, 22);

        jblNumeroConciertosActualizarCantante.setText("Numero de Conciertos:");
        jpanelA.add(jblNumeroConciertosActualizarCantante);
        jblNumeroConciertosActualizarCantante.setBounds(66, 397, 133, 16);

        txtNumeroConciertos.setEnabled(false);
        jpanelA.add(txtNumeroConciertos);
        txtNumeroConciertos.setBounds(280, 390, 164, 22);

        jblNumeroGiras.setText("Numero de Giras:");
        jpanelA.add(jblNumeroGiras);
        jblNumeroGiras.setBounds(66, 446, 133, 16);

        txtNumeroGiras.setEnabled(false);
        jpanelA.add(txtNumeroGiras);
        txtNumeroGiras.setBounds(280, 440, 164, 22);

        jblIdActualizarCantante.setText("ID:");
        jpanelA.add(jblIdActualizarCantante);
        jblIdActualizarCantante.setBounds(72, 37, 14, 16);

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        jpanelA.add(txtID);
        txtID.setBounds(280, 30, 164, 22);

        bntActualizar.setText("Actualizar");
        bntActualizar.setEnabled(false);
        bntActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntActualizarActionPerformed(evt);
            }
        });
        jpanelA.add(bntActualizar);
        bntActualizar.setBounds(341, 526, 82, 23);

        jblNombreActualizarCantante.setText("Nombre:");
        jpanelA.add(jblNombreActualizarCantante);
        jblNombreActualizarCantante.setBounds(72, 80, 58, 16);

        txtNombre.setEnabled(false);
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jpanelA.add(txtNombre);
        txtNombre.setBounds(280, 70, 164, 22);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jpanelA.add(btnCancelar);
        btnCancelar.setBounds(441, 526, 76, 23);

        jblApellidoActualizarCantante.setText("Apellido:");
        jpanelA.add(jblApellidoActualizarCantante);
        jblApellidoActualizarCantante.setBounds(72, 124, 58, 16);

        txtApellido.setEnabled(false);
        jpanelA.add(txtApellido);
        txtApellido.setBounds(280, 120, 164, 22);

        jblEdadActualizarCantante.setText("Edad:");
        jpanelA.add(jblEdadActualizarCantante);
        jblEdadActualizarCantante.setBounds(72, 158, 58, 16);

        txtEdad.setEnabled(false);
        jpanelA.add(txtEdad);
        txtEdad.setBounds(280, 160, 164, 22);

        jblNacionalidadActualizarCantante.setText("Nacionalidad:");
        jpanelA.add(jblNacionalidadActualizarCantante);
        jblNacionalidadActualizarCantante.setBounds(72, 192, 86, 16);

        txtNacionalidad.setEnabled(false);
        jpanelA.add(txtNacionalidad);
        txtNacionalidad.setBounds(280, 200, 164, 22);

        jblSalarioActualizarCantante.setText("Salario:");
        jpanelA.add(jblSalarioActualizarCantante);
        jblSalarioActualizarCantante.setBounds(72, 239, 86, 16);

        txtSalario.setEnabled(false);
        jpanelA.add(txtSalario);
        txtSalario.setBounds(280, 240, 164, 22);

        jblNombreArtisticoActualizarCantante.setText("Nombre Artistico:");
        jpanelA.add(jblNombreArtisticoActualizarCantante);
        jblNombreArtisticoActualizarCantante.setBounds(72, 273, 118, 16);

        txtNombreArtistico.setEnabled(false);
        jpanelA.add(txtNombreArtistico);
        txtNombreArtistico.setBounds(280, 270, 164, 22);

        jblGeneroMusicalActualizarCantante.setText("Genero Musical:");
        jpanelA.add(jblGeneroMusicalActualizarCantante);
        jblGeneroMusicalActualizarCantante.setBounds(72, 307, 118, 16);

        txtGeneroMusical.setEnabled(false);
        jpanelA.add(txtGeneroMusical);
        txtGeneroMusical.setBounds(280, 300, 164, 22);

        jblNumeroSencillosActualizarCantante.setText("Numero de Sencillos:");
        jpanelA.add(jblNumeroSencillosActualizarCantante);
        jblNumeroSencillosActualizarCantante.setBounds(66, 349, 118, 16);

        bntBuscar.setText("Buscar");
        bntBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntBuscarActionPerformed(evt);
            }
        });
        jpanelA.add(bntBuscar);
        bntBuscar.setBounds(480, 30, 72, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Actulizar.png"))); // NOI18N
        jpanelA.add(jLabel1);
        jLabel1.setBounds(30, 30, 32, 32);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ImgenCantante.jpg"))); // NOI18N
        jpanelA.add(jLabel2);
        jLabel2.setBounds(11, 19, 590, 640);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelA, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanelA, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntActualizarActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(txtID.getText());
        String nombre = txtNombre.getText();
        String apellido = txtApellido.getText();
        int edad = Integer.parseInt(txtEdad.getText());
        String nacionalidad = txtNacionalidad.getText();
        double salario = Double.parseDouble(txtSalario.getText());
        String nombreArtistico = txtNombreArtistico.getText();
        String genero = txtGeneroMusical.getText();
        int numeroSencillos = Integer.parseInt(txtNumeroSencillos.getText());
        int numeroConciertos = Integer.parseInt(txtNumeroConciertos.getText());
        int numeroGiras = Integer.parseInt(txtNumeroGiras.getText());
        Cantante cantante = new Cantante(nombreArtistico, genero, numeroSencillos, numeroConciertos, numeroGiras, id, nombre, apellido, edad, nacionalidad, salario);
        cantante.setDiscos(listaDiscos);
        controladorCantante.actualizar(cantante);
        this.limpiarCampos();
        JOptionPane.showMessageDialog(this, mensajes.getString("joption.seactualizoelcantante")); 
        System.out.println(controladorCantante.verCantantes());
        this.visibilidad(false);
        bntActualizar.setEnabled(false);
        this.limpiarCampos();
        bntBuscar.setEnabled(true);
    }//GEN-LAST:event_bntActualizarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        txtID.setText("");
        this.setVisible(false);
        this.visibilidad(false);
        bntActualizar.setEnabled(false);
        this.limpiarCampos();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void bntBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntBuscarActionPerformed
        // TODO add your handling code here:
        if (txtID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, mensajes.getString("joption.noestalleno")); 
        }else{
            Cantante cantante = controladorCantante.buscarCantante(Integer.parseInt(txtID.getText()));
            
            if (cantante!=null) {
                this.visibilidad(true);
                txtNombre.setText(cantante.getNombre());
                txtApellido.setText(cantante.getApellido());
                txtEdad.setText( String.valueOf(cantante.getEdad()));
                txtNacionalidad.setText(cantante.getNacionalidad());
                txtNacionalidad.setText(cantante.getNacionalidad());
                txtSalario.setText(String.valueOf(cantante.calcularSalario()));
                txtNombreArtistico.setText(cantante.getNombreArtistico());
                txtGeneroMusical.setText(cantante.getGeneroMusical());
                txtNumeroSencillos.setText(String.valueOf(cantante.getNumeroDeSencillos()));
                txtNumeroConciertos.setText(String.valueOf(cantante.getNumeroDeConciertos()));
                txtNumeroGiras.setText(String.valueOf(cantante.getNumeroDeGiras()));
                bntActualizar.setEnabled(true);
                bntBuscar.setEnabled(false);
                listaDiscos = cantante.getDiscos();
            }else{
                JOptionPane.showMessageDialog(this, mensajes.getString("joption.noexiste")); 
            }
        }
    }//GEN-LAST:event_bntBuscarActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
       
    }//GEN-LAST:event_formInternalFrameActivated

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        this.limpiarCampos();
    }//GEN-LAST:event_formInternalFrameClosing
    
    private void visibilidad(boolean variable){
        
        txtID.setEnabled(!variable);
        txtNombre.setEnabled(variable);
        txtApellido.setEnabled(variable);
        txtEdad.setEnabled(variable);
        txtNacionalidad.setEnabled(variable);
        txtSalario.setEnabled(variable);
        txtNombreArtistico.setEnabled(variable);
        txtNumeroConciertos.setEnabled(variable);
        txtNumeroSencillos.setEnabled(variable);
        txtNumeroGiras.setEnabled(variable);
        txtGeneroMusical.setEnabled(variable);
        
    }
    
    private void limpiarCampos(){
        txtID.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtEdad.setText("");
        txtNacionalidad.setText("");
        txtSalario.setText("");
        txtNombreArtistico.setText("");
        txtNumeroConciertos.setText("");
        txtNumeroSencillos.setText("");
        txtNumeroGiras.setText("");
        txtGeneroMusical.setText(""); 
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntActualizar;
    private javax.swing.JButton bntBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jblApellidoActualizarCantante;
    private javax.swing.JLabel jblEdadActualizarCantante;
    private javax.swing.JLabel jblGeneroMusicalActualizarCantante;
    private javax.swing.JLabel jblIdActualizarCantante;
    private javax.swing.JLabel jblNacionalidadActualizarCantante;
    private javax.swing.JLabel jblNombreActualizarCantante;
    private javax.swing.JLabel jblNombreArtisticoActualizarCantante;
    private javax.swing.JLabel jblNumeroConciertosActualizarCantante;
    private javax.swing.JLabel jblNumeroGiras;
    private javax.swing.JLabel jblNumeroSencillosActualizarCantante;
    private javax.swing.JLabel jblSalarioActualizarCantante;
    private javax.swing.JPanel jpanelA;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtGeneroMusical;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNacionalidad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreArtistico;
    private javax.swing.JTextField txtNumeroConciertos;
    private javax.swing.JTextField txtNumeroGiras;
    private javax.swing.JTextField txtNumeroSencillos;
    private javax.swing.JTextField txtSalario;
    // End of variables declaration//GEN-END:variables
}
