/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.practica7.lucerojustin.tacurijhonatan.vista.cantante;

import ec.edu.ups.practica7.lucerojustin.tacurijhonatan.controlador.ControladorCantante;
import ec.edu.ups.practica7.lucerojustin.tacurijhonatan.modelo.Cantante;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author ESTUDIANTE
 */
public class EliminarCantante extends javax.swing.JInternalFrame {
    private ControladorCantante controladorCantante;
    private ResourceBundle mensajes;
    /**
     * Creates new form VentanaBuscarCantante
     */
    public EliminarCantante(ControladorCantante controladorCantante) {
        initComponents();
        this.controladorCantante = controladorCantante;
        
    }
    
    public void cambiarIdioma(Locale localizacion){
        mensajes = ResourceBundle.getBundle("mensajes.mensaje", localizacion);
        jblIdEliminarCantante.setText(mensajes.getString("ventana.id"));
        jblNombreEliminarCantante.setText(mensajes.getString("ventana.nombre"));
        jblApellidoEliminarCantante.setText(mensajes.getString("ventana.apellido"));
        jblEdadEliminarCantante.setText(mensajes.getString("ventana.edad"));
        jblSalarioEliminarCantante.setText(mensajes.getString("ventana.salario"));
        jblNacionalidadEliminarCantante.setText(mensajes.getString("ventana.nacionalidad"));
        jblGeneroMusicalEliminarCantante.setText(mensajes.getString("ventanaCantante.generomusical"));
        jblNumeroConciertosEliminarCantante.setText(mensajes.getString("ventanaCantante.numeroconciertos"));
        jblNumeroGirasEliminarCantante.setText(mensajes.getString("ventanaCantante.numerogiras"));
        jblNumeroSencillosEliminarCantante.setText(mensajes.getString("ventanaCantante.numerosencillos"));
        jblNombreArEliminarCantante.setText(mensajes.getString("ventanaCantante.nombreartistico"));
        btnCancelar.setText(mensajes.getString("boton.cancelar"));
        bntBuscarr.setText(mensajes.getString("boton.buscar"));
        bntEliminar.setText(mensajes.getString("boton.eliminar"));
        Border borde = BorderFactory.createTitledBorder(mensajes.getString("panel.eliminarcantante"));
        jpanelA.setBorder(borde);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelA = new javax.swing.JPanel();
        jblIdEliminarCantante = new javax.swing.JLabel();
        jblNombreEliminarCantante = new javax.swing.JLabel();
        jblApellidoEliminarCantante = new javax.swing.JLabel();
        jblEdadEliminarCantante = new javax.swing.JLabel();
        jblNacionalidadEliminarCantante = new javax.swing.JLabel();
        jblSalarioEliminarCantante = new javax.swing.JLabel();
        jblNombreArEliminarCantante = new javax.swing.JLabel();
        jblGeneroMusicalEliminarCantante = new javax.swing.JLabel();
        jblNumeroSencillosEliminarCantante = new javax.swing.JLabel();
        jblNumeroConciertosEliminarCantante = new javax.swing.JLabel();
        jblNumeroGirasEliminarCantante = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtNacionalidad = new javax.swing.JTextField();
        txtSalario = new javax.swing.JTextField();
        txtNombreArtistico = new javax.swing.JTextField();
        txtGeneroMusical = new javax.swing.JTextField();
        txtNumeroSencillos = new javax.swing.JTextField();
        txtNumeroConciertos = new javax.swing.JTextField();
        txtNumeroGiras = new javax.swing.JTextField();
        bntEliminar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        bntBuscarr = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jpanelA.setBorder(javax.swing.BorderFactory.createTitledBorder("ELIMINAR CANTANTE"));
        jpanelA.setLayout(null);

        jblIdEliminarCantante.setText("ID:");
        jpanelA.add(jblIdEliminarCantante);
        jblIdEliminarCantante.setBounds(126, 80, 14, 16);

        jblNombreEliminarCantante.setText("Nombre:");
        jpanelA.add(jblNombreEliminarCantante);
        jblNombreEliminarCantante.setBounds(126, 130, 58, 16);

        jblApellidoEliminarCantante.setText("Apellido:");
        jpanelA.add(jblApellidoEliminarCantante);
        jblApellidoEliminarCantante.setBounds(126, 170, 58, 16);

        jblEdadEliminarCantante.setText("Edad:");
        jpanelA.add(jblEdadEliminarCantante);
        jblEdadEliminarCantante.setBounds(126, 210, 58, 16);

        jblNacionalidadEliminarCantante.setText("Nacionalidad:");
        jpanelA.add(jblNacionalidadEliminarCantante);
        jblNacionalidadEliminarCantante.setBounds(126, 247, 86, 16);

        jblSalarioEliminarCantante.setText("Salario:");
        jpanelA.add(jblSalarioEliminarCantante);
        jblSalarioEliminarCantante.setBounds(126, 284, 86, 16);

        jblNombreArEliminarCantante.setText("Nombre Artistico:");
        jpanelA.add(jblNombreArEliminarCantante);
        jblNombreArEliminarCantante.setBounds(126, 324, 118, 16);

        jblGeneroMusicalEliminarCantante.setText("Genero Musical:");
        jpanelA.add(jblGeneroMusicalEliminarCantante);
        jblGeneroMusicalEliminarCantante.setBounds(126, 364, 118, 16);

        jblNumeroSencillosEliminarCantante.setText("Numero de Sencillos:");
        jpanelA.add(jblNumeroSencillosEliminarCantante);
        jblNumeroSencillosEliminarCantante.setBounds(126, 404, 118, 16);

        jblNumeroConciertosEliminarCantante.setText("Numero de Conciertos:");
        jpanelA.add(jblNumeroConciertosEliminarCantante);
        jblNumeroConciertosEliminarCantante.setBounds(126, 441, 133, 16);

        jblNumeroGirasEliminarCantante.setText("Numero de Giras:");
        jpanelA.add(jblNumeroGirasEliminarCantante);
        jblNumeroGirasEliminarCantante.setBounds(126, 478, 133, 16);
        jpanelA.add(txtID);
        txtID.setBounds(325, 77, 164, 22);

        txtNombre.setEditable(false);
        txtNombre.setEnabled(false);
        jpanelA.add(txtNombre);
        txtNombre.setBounds(325, 127, 164, 22);

        txtApellido.setEditable(false);
        txtApellido.setEnabled(false);
        jpanelA.add(txtApellido);
        txtApellido.setBounds(325, 167, 164, 22);

        txtEdad.setEditable(false);
        txtEdad.setEnabled(false);
        jpanelA.add(txtEdad);
        txtEdad.setBounds(325, 207, 164, 22);

        txtNacionalidad.setEditable(false);
        txtNacionalidad.setEnabled(false);
        jpanelA.add(txtNacionalidad);
        txtNacionalidad.setBounds(325, 241, 164, 22);

        txtSalario.setEditable(false);
        txtSalario.setEnabled(false);
        jpanelA.add(txtSalario);
        txtSalario.setBounds(325, 281, 164, 22);

        txtNombreArtistico.setEditable(false);
        txtNombreArtistico.setEnabled(false);
        jpanelA.add(txtNombreArtistico);
        txtNombreArtistico.setBounds(325, 321, 164, 22);

        txtGeneroMusical.setEditable(false);
        txtGeneroMusical.setEnabled(false);
        jpanelA.add(txtGeneroMusical);
        txtGeneroMusical.setBounds(325, 361, 164, 22);

        txtNumeroSencillos.setEditable(false);
        txtNumeroSencillos.setEnabled(false);
        jpanelA.add(txtNumeroSencillos);
        txtNumeroSencillos.setBounds(325, 401, 164, 22);

        txtNumeroConciertos.setEditable(false);
        txtNumeroConciertos.setEnabled(false);
        jpanelA.add(txtNumeroConciertos);
        txtNumeroConciertos.setBounds(325, 435, 164, 22);

        txtNumeroGiras.setEditable(false);
        txtNumeroGiras.setEnabled(false);
        jpanelA.add(txtNumeroGiras);
        txtNumeroGiras.setBounds(325, 475, 164, 22);

        bntEliminar.setText("Eliminar");
        bntEliminar.setEnabled(false);
        bntEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntEliminarActionPerformed(evt);
            }
        });
        jpanelA.add(bntEliminar);
        bntEliminar.setBounds(312, 503, 73, 23);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jpanelA.add(btnCancelar);
        btnCancelar.setBounds(403, 503, 76, 23);

        bntBuscarr.setText("Buscar");
        bntBuscarr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntBuscarrActionPerformed(evt);
            }
        });
        jpanelA.add(bntBuscarr);
        bntBuscarr.setBounds(524, 77, 72, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Eliminar.png"))); // NOI18N
        jpanelA.add(jLabel1);
        jLabel1.setBounds(40, 40, 32, 32);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/EliminarCant.jpg"))); // NOI18N
        jpanelA.add(jLabel2);
        jLabel2.setBounds(10, 16, 590, 530);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelA, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelA, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEliminarActionPerformed
        // TODO add your handling code here:
        int respuesta=JOptionPane.showConfirmDialog(this, mensajes.getString("joption.eliminarcantante")); 
        if (respuesta==JOptionPane.YES_OPTION) {
            controladorCantante.eliminar(controladorCantante.buscarCantante(Integer.parseInt(txtID.getText())));
            JOptionPane.showMessageDialog(this, mensajes.getString("joption.cantnteeliminado")); 
            txtID.setText("");
            this.limpiarCampos();
        }else{
            JOptionPane.showMessageDialog(this, mensajes.getString("joption.noseeliminocantante")); 
        }
    }//GEN-LAST:event_bntEliminarActionPerformed
    
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        txtID.setText("");
        this.limpiarCampos();
        this.setVisible(false);
        
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void bntBuscarrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntBuscarrActionPerformed
        // TODO add your handling code here:
        if (txtID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, mensajes.getString("joption.noestalleno")); 
        }else{
            Cantante cantanteTempo = controladorCantante.buscarCantante(Integer.parseInt(txtID.getText()));
            if (cantanteTempo !=null) {
                txtNombre.setText(cantanteTempo.getNombre());
                txtApellido.setText(cantanteTempo.getApellido());
                txtEdad.setText( String.valueOf(cantanteTempo.getEdad()));
                txtNacionalidad.setText(cantanteTempo.getNacionalidad());
                txtNacionalidad.setText(cantanteTempo.getNacionalidad());
                txtSalario.setText(String.valueOf(cantanteTempo.calcularSalario()));
                txtNombreArtistico.setText(cantanteTempo.getNombreArtistico());
                txtGeneroMusical.setText(cantanteTempo.getGeneroMusical());
                txtNumeroSencillos.setText(String.valueOf(cantanteTempo.getNumeroDeSencillos()));
                txtNumeroConciertos.setText(String.valueOf(cantanteTempo.getNumeroDeConciertos()));
                txtNumeroGiras.setText(String.valueOf(cantanteTempo.getNumeroDeGiras()));
                bntEliminar.setEnabled(true);
            }else{
                this.limpiarCampos();
                JOptionPane.showMessageDialog(this, mensajes.getString("joption.noexiste")); 
               
            }
        }
    }//GEN-LAST:event_bntBuscarrActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        this.limpiarCampos();
    }//GEN-LAST:event_formInternalFrameClosing
    private void limpiarCampos(){
        
        txtNombre.setText("");
        txtApellido.setText("");
        txtEdad.setText("");
        txtNacionalidad.setText("");
        txtSalario.setText("");
        txtNombreArtistico.setText("");
        txtNumeroConciertos.setText("");
        txtNumeroSencillos.setText("");
        txtNumeroGiras.setText("");
        txtGeneroMusical.setText(""); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntBuscarr;
    private javax.swing.JButton bntEliminar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jblApellidoEliminarCantante;
    private javax.swing.JLabel jblEdadEliminarCantante;
    private javax.swing.JLabel jblGeneroMusicalEliminarCantante;
    private javax.swing.JLabel jblIdEliminarCantante;
    private javax.swing.JLabel jblNacionalidadEliminarCantante;
    private javax.swing.JLabel jblNombreArEliminarCantante;
    private javax.swing.JLabel jblNombreEliminarCantante;
    private javax.swing.JLabel jblNumeroConciertosEliminarCantante;
    private javax.swing.JLabel jblNumeroGirasEliminarCantante;
    private javax.swing.JLabel jblNumeroSencillosEliminarCantante;
    private javax.swing.JLabel jblSalarioEliminarCantante;
    private javax.swing.JPanel jpanelA;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtGeneroMusical;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNacionalidad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreArtistico;
    private javax.swing.JTextField txtNumeroConciertos;
    private javax.swing.JTextField txtNumeroGiras;
    private javax.swing.JTextField txtNumeroSencillos;
    private javax.swing.JTextField txtSalario;
    // End of variables declaration//GEN-END:variables
}
