/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package ec.edu.ups.practica.cantante.compositor.interfaces.vista;

import ec.edu.ups.practica.cantante.compositor.interfaces.controlador.ControladorCantante;
import ec.edu.ups.practica.cantante.compositor.interfaces.dao.CantanteDao;
import ec.edu.ups.practica.cantante.compositor.interfaces.idao.ICantanteDao;
import ec.edu.ups.practica.cantante.compositor.interfaces.vista.cantante.VentanaBuscarCantante;
import ec.edu.ups.practica.cantante.compositor.interfaces.vista.cantante.VentanaCrearCantante;

/**
 *
 * @author ESTUDIANTE
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    private ControladorCantante controladorCantante;
    private ICantanteDao cantanteDao;
    
    private VentanaCrearCantante ventanaCrearCantante;
    private VentanaBuscarCantante ventanaBuscarCantante;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        cantanteDao = new CantanteDao();
        controladorCantante = new ControladorCantante(cantanteDao) ;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        itemCrearCantante = new javax.swing.JMenuItem();
        itemActualizarCantante = new javax.swing.JMenuItem();
        itemBuscarCantante = new javax.swing.JMenuItem();
        itemEliminarCantante = new javax.swing.JMenuItem();
        itemListarCantante = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        itemCrearCompositor = new javax.swing.JMenuItem();
        itemActualizarCompositor = new javax.swing.JMenuItem();
        itemBuscarCompositor = new javax.swing.JMenuItem();
        itemEliminarCompositor = new javax.swing.JMenuItem();
        itemListarCompositor = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        itemSalirMenu = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Cantante");

        itemCrearCantante.setMnemonic('o');
        itemCrearCantante.setText("Crear");
        itemCrearCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCrearCantanteActionPerformed(evt);
            }
        });
        fileMenu.add(itemCrearCantante);

        itemActualizarCantante.setMnemonic('s');
        itemActualizarCantante.setText("Actualizar");
        fileMenu.add(itemActualizarCantante);

        itemBuscarCantante.setMnemonic('a');
        itemBuscarCantante.setText("Buscar");
        itemBuscarCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBuscarCantanteActionPerformed(evt);
            }
        });
        fileMenu.add(itemBuscarCantante);

        itemEliminarCantante.setMnemonic('x');
        itemEliminarCantante.setText("Eliminar");
        itemEliminarCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEliminarCantanteActionPerformed(evt);
            }
        });
        fileMenu.add(itemEliminarCantante);

        itemListarCantante.setText("Listar");
        fileMenu.add(itemListarCantante);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Compositor");

        itemCrearCompositor.setMnemonic('t');
        itemCrearCompositor.setText("Crear");
        itemCrearCompositor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCrearCompositorActionPerformed(evt);
            }
        });
        editMenu.add(itemCrearCompositor);

        itemActualizarCompositor.setMnemonic('y');
        itemActualizarCompositor.setText("Actualizar");
        editMenu.add(itemActualizarCompositor);

        itemBuscarCompositor.setMnemonic('p');
        itemBuscarCompositor.setText("Buscar");
        itemBuscarCompositor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBuscarCompositorActionPerformed(evt);
            }
        });
        editMenu.add(itemBuscarCompositor);

        itemEliminarCompositor.setMnemonic('d');
        itemEliminarCompositor.setText("Eliminar");
        editMenu.add(itemEliminarCompositor);

        itemListarCompositor.setText("Listar");
        editMenu.add(itemListarCompositor);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Opciones");

        itemSalirMenu.setMnemonic('c');
        itemSalirMenu.setText("Salir");
        helpMenu.add(itemSalirMenu);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemEliminarCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEliminarCantanteActionPerformed
        System.exit(0);
    }//GEN-LAST:event_itemEliminarCantanteActionPerformed

    private void itemCrearCompositorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCrearCompositorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemCrearCompositorActionPerformed

    private void itemBuscarCompositorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBuscarCompositorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemBuscarCompositorActionPerformed

    private void itemCrearCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCrearCantanteActionPerformed
        if(ventanaCrearCantante == null){
            ventanaCrearCantante = new VentanaCrearCantante(controladorCantante);
            desktopPane.add(ventanaCrearCantante);
        }
        ventanaCrearCantante.setVisible(true); 
    }//GEN-LAST:event_itemCrearCantanteActionPerformed

    private void itemBuscarCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBuscarCantanteActionPerformed
        // TODO add your handling code here:
        if(ventanaBuscarCantante == null){
            ventanaBuscarCantante = new VentanaBuscarCantante(controladorCantante);
            desktopPane.add(ventanaBuscarCantante);
        }
        ventanaBuscarCantante.setVisible(true); 
    }//GEN-LAST:event_itemBuscarCantanteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem itemActualizarCantante;
    private javax.swing.JMenuItem itemActualizarCompositor;
    private javax.swing.JMenuItem itemBuscarCantante;
    private javax.swing.JMenuItem itemBuscarCompositor;
    private javax.swing.JMenuItem itemCrearCantante;
    private javax.swing.JMenuItem itemCrearCompositor;
    private javax.swing.JMenuItem itemEliminarCantante;
    private javax.swing.JMenuItem itemEliminarCompositor;
    private javax.swing.JMenuItem itemListarCantante;
    private javax.swing.JMenuItem itemListarCompositor;
    private javax.swing.JMenuItem itemSalirMenu;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
